---
title: "1) hpf18_PreProcessing "
author: "Kane"
date: "August 8th, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

Setting working directory
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "D:/scRNAseq/wagnerFish/zebrafishNMp/")
```

Importing libraries
```{r echo=FALSE}
###  Clearing workspace and loading the required packages
library(scater)
library(SingleCellExperiment)
library(tidyverse)
library(org.Dr.eg.db)

```


```{r Importing Dataset} 

# Raw count matrix, and prefix column names with timepoint

count_matrix <- read_csv("Raw/18hpf_rawFiles/GSM3067194_18hpf.csv") %>% column_to_rownames("Row")
colnames(count_matrix) <- paste0("18hpf", colnames(count_matrix)) # Rownames of Metadata and Colnames of matrix must match

```

```{r echo=TRUE}
# Creating SCE object

hpf18 <- SingleCellExperiment(assays = list(counts = as.matrix(count_matrix)), colData = metadata)

ensembl <- mapIds(org.Dr.eg.db, keys=rownames(hpf18), keytype = "SYMBOL",
                  column = "ENSEMBL")
rowData(hpf18)$ENSEMBL <- ensembl

hpf18 <- calculateQCMetrics(hpf18, exprs_values = "counts", 
                            feature_controls = NULL,
                            cell_controls = NULL, percent_top = c(50, 100, 200, 500),
                            detection_limit = 0, use_spikes = FALSE, compact = FALSE)

```

```{r Quality Check , fig.height=10, fig.width=20}

#Cell level QC metrics
par(mfrow = c(1,2))

hist(hpf18$total_counts/1e3, xlab="Library sizes (thousands)", main="",  breaks=20, col="grey80", ylab="Number of cells")
hist(hpf18$total_features_by_counts, xlab="Number of expressed genes", main="", 
    breaks=20, col="grey80", ylab="Number of cells")


# Remove Cells wit log-library and log-feature sizes that are more than 3 median absolute deviations away from median metric values.

libsize.drop <- isOutlier(hpf18$total_counts, nmads=3, type="lower", log=TRUE)
feature.drop <- isOutlier(hpf18$total_features_by_counts, nmads=3, type="lower", log=TRUE)
hpf18 <- hpf18[,!(libsize.drop | feature.drop)]
data.frame(ByLibSize=sum(libsize.drop), ByFeature=sum(feature.drop), 
           Remaining=ncol(hpf18))

# Gene level QC metrics

ave.counts <- calcAverage(hpf18, use_size_factors=FALSE)
hist(log10(ave.counts), breaks=100, main="", col="grey",
    xlab=expression(Log[10]~"average count"))
rowData(hpf18)$ave.count <- ave.counts

# Only keep genes with average counts across all cells that's greater than 0. Removes genes that are not expressed.

to.keep <- ave.counts > 0 #Check filter here
hpf18<- hpf18[to.keep,]
dim(hpf18)

saveRDS(hpf18, file = "hpf18_QCed.rds" )

```

