--- 
title: "Single-cell RNA seq analysis of zebrafish NMps"
author: "Kane Toh, Giles Harper-Donnelly  "
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Single-cell RNA-seq analysis workshop series for AMA and Steventon labs
held in June 2020."
---

# Introduction

This is the github repository for the “Hands-on guide to single cell RNA seq analysis in R computational workshop” series given to the AMA and Steventon labs on 4th June 2020.

## Objectives

- The volume of online resources on the single-cell field is vast. We hope that this short practical session will help point you in the right direction in conducting your own scRNA-seq data analysis by:
- Highlighting the relevant reading material, scRNA-seq packages and other resources available for further study.
- Sharing practical advice on dealing with issues that you may encounter in your own analyses.
- Providing you with code as starting material to tinker with.

## Description:
We will be studying the scRNA-seq dataset of 18hpf zebrafish embryos, with a focus on examining the gene expression states of the tailbud Neuromesodermal progenitors.

Additioanlly we will be taking a closer look at some key techniques, highlighting important details to keep in mind both when implementing and evaluating single-cell anaylsis.

We hope that this will provide a good starting point for getting to grips with this fast-moving field, and encourage you to contact us for further disucssion or advice if needed.

## Links
[Reference paper](https://science.sciencemag.org/content/360/6392/981.full)

[Dataset repository](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3067194)

## Created by:
- Kane Toh
- Giles Harper-Donnelly 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, messages = FALSE, warning = FALSE)
rm(list=ls())
gc()

```

