install.packages("rmarkdown")
install.packages("httr")
install.packages("RColorBrewer")
install.packages("colorspace")
install.packages("viridis")
install.packages("tidyverse")
install.packages("pheatmap")
install.packages("extrafont")
install.packages("gam")
install.packages("devtools")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("slingshot")
BiocManager::install("scater")
BiocManager::install("SingleCellExperiment")
BiocManager::install("org.Dr.eg.db")
BiocManager::install("scran")
BiocManager::install("slingshot")
BiocManager::install("tradeSeq")
