install.packages("rmarkdown")
install.packages("RColorBrewer")
install.packages("colorspace")
install.packages("viridis")
install.packages("tidyverse")
install.packages("pheatmap")
install.packages("extrafont")
install.packages("gam")
install.packages("devtools")
install.packages("gridExtra")
install.packages('Seurat')
install.packages("cowplot")
install.packages("scales")
install.packages("NMF")
install.packages("mclust")
install.packages("cluster")


if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("slingshot")
BiocManager::install("scater")
BiocManager::install("SingleCellExperiment")
BiocManager::install("org.Dr.eg.db")
BiocManager::install("scran")
BiocManager::install("slingshot")
BiocManager::install("tradeSeq")
BiocManager::install("clusterExperiment")
